ERROR: SynthesisMessage(entry=MetadataEntry(type='aws:cdk:error', data='AwsSolutions-S1: The S3 Bucket has server access logs disabled. The bucket should have server access logging enabled to provide detailed records for the requests that are made to the bucket.\n', trace=['Annotations.addMessage (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1978)', 'Annotations.addError (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1440)', 'AnnotationLogger.onNonCompliance (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-logger.js:30:61)', '/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:55', 'Array.forEach (<anonymous>)', 'AwsSolutionsChecks.applyRule (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:38)', 'AwsSolutionsChecks.checkStorage (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:245:14)', 'AwsSolutionsChecks.visit (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:65:18)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4537)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'invokeAspectsV2 (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:3163)', 'synthesize (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1760)', 'App.synth (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/stage.js:1:2770)', 'toMessages (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:3171)', 'Annotations.fromStack (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:760)', '/tmp/tmpozw18_iq/lib/program.js:315:151', 'Kernel._Kernel_ensureSync (/tmp/tmpozw18_iq/lib/program.js:916:24)', 'Kernel.sinvoke (/tmp/tmpozw18_iq/lib/program.js:315:102)', 'KernelHost.processRequest (/tmp/tmpozw18_iq/lib/program.js:15479:36)', 'KernelHost.run (/tmp/tmpozw18_iq/lib/program.js:15439:22)', 'Immediate._onImmediate (/tmp/tmpozw18_iq/lib/program.js:15440:45)', 'process.processImmediate (node:internal/timers:491:21)']), id='/AppStack/LogBucket/Bucket/Resource', level=<SynthesisMessageLevel.ERROR: 'ERROR'>)
WARN: SynthesisMessage(entry=MetadataEntry(type='aws:cdk:warning', data='AwsSolutions-DDB3: The DynamoDB table does not have Point-in-time Recovery enabled. DynamoDB continuous backups represent an additional layer of insurance against accidental loss of data on top of on-demand backups. The DynamoDB service can back up the data with per-second granularity and restore it to any single second from the time PITR was enabled up to the prior 35 days.\n', trace=['Annotations.addMessage (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1978)', 'Annotations.addWarning (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1002)', 'AnnotationLogger.onNonCompliance (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-logger.js:33:61)', '/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:55', 'Array.forEach (<anonymous>)', 'AwsSolutionsChecks.applyRule (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:38)', 'AwsSolutionsChecks.checkDatabases (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:365:14)', 'AwsSolutionsChecks.visit (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:66:18)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4537)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'invokeAspectsV2 (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:3163)', 'synthesize (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1760)', 'App.synth (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/stage.js:1:2770)', 'toMessages (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:3171)', 'Annotations.fromStack (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:760)', '/tmp/tmpozw18_iq/lib/program.js:315:151', 'Kernel._Kernel_ensureSync (/tmp/tmpozw18_iq/lib/program.js:916:24)', 'Kernel.sinvoke (/tmp/tmpozw18_iq/lib/program.js:315:102)', 'KernelHost.processRequest (/tmp/tmpozw18_iq/lib/program.js:15479:36)', 'KernelHost.run (/tmp/tmpozw18_iq/lib/program.js:15439:22)', 'Immediate._onImmediate (/tmp/tmpozw18_iq/lib/program.js:15440:45)', 'process.processImmediate (node:internal/timers:491:21)']), id='/AppStack/Book/Table/Resource', level=<SynthesisMessageLevel.WARNING: 'WARNING'>)
WARN: SynthesisMessage(entry=MetadataEntry(type='aws:cdk:warning', data='AwsSolutions-APIG3: The REST API stage is not associated with AWS WAFv2 web ACL. AWS WAFv2 is a web application firewall that helps protect web applications and APIs from attacks by allowing configured rules to allow, block, or monitor (count) web requests based on customizable rules and conditions that are defined.\n', trace=['Annotations.addMessage (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1978)', 'Annotations.addWarning (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/annotations.js:1:1002)', 'AnnotationLogger.onNonCompliance (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-logger.js:33:61)', '/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:55', 'Array.forEach (<anonymous>)', 'AwsSolutionsChecks.applyRule (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/nag-pack.js:79:38)', 'AwsSolutionsChecks.checkNetworkDelivery (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:685:14)', 'AwsSolutionsChecks.visit (/tmp/jsii-kernel-jl78BE/node_modules/cdk-nag/lib/packs/aws-solutions.js:67:18)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4537)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'recurse (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:4772)', 'invokeAspectsV2 (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:3163)', 'synthesize (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1760)', 'App.synth (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/core/lib/stage.js:1:2770)', 'toMessages (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:3171)', 'Annotations.fromStack (/tmp/jsii-kernel-jl78BE/node_modules/aws-cdk-lib/assertions/lib/annotations.js:1:760)', '/tmp/tmpozw18_iq/lib/program.js:315:151', 'Kernel._Kernel_ensureSync (/tmp/tmpozw18_iq/lib/program.js:916:24)', 'Kernel.sinvoke (/tmp/tmpozw18_iq/lib/program.js:315:102)', 'KernelHost.processRequest (/tmp/tmpozw18_iq/lib/program.js:15479:36)', 'KernelHost.run (/tmp/tmpozw18_iq/lib/program.js:15439:22)', 'Immediate._onImmediate (/tmp/tmpozw18_iq/lib/program.js:15440:45)', 'process.processImmediate (node:internal/timers:491:21)']), id='/AppStack/Api/LambdaRestApi/DeploymentStage.v1/Resource', level=<SynthesisMessageLevel.WARNING: 'WARNING'>)
